name: CI
on:
  push:
    branches:
      - main
  pull_request:

env:
  CI: true

jobs:
  main:
    runs-on: ubuntu-latest

    services:
      kratos:
        image: oryd/kratos:v1.0.0
        ports:
          - '44330:4433'
          - '44340:4434'
        options: >-
          --health-cmd "wget -nv --spider -t1 http://localhost:4433/health/ready || exit 1"
          --health-interval 3s
          --health-timeout 2s
          --health-retries 5
          --health-start-period 5s

      keto:
        image: oryd/keto:v0.11.1
        ports:
          - '44660:4466'
          - '44670:4467'
        volumes:
          - ${{ github.workspace }}/packages/keto-client-wrapper/test/namespaces.ts:/home/ory/namespaces.ts
        options: >-
          --health-cmd "wget -nv --spider -t1 http://localhost:4466/health/ready || exit 1"
          --health-interval 3s
          --health-timeout 2s
          --health-retries 5
          --health-start-period 5s
        env:
          DSN: memory
          NAMESPACES_LOCATION: /home/ory/namespaces.ts

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # restart keto to allow volume binding to be effective
      - uses: docker://docker
        with:
          args: docker restart keto

      # Cache node_modules
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - run: npm ci

      - uses: nrwl/nx-set-shas@v4

      - uses: 8BitJonny/gh-get-current-pr@2.2.0
        id: current-pr

      - if: steps.current-pr.outputs.number != 'null'
        # This line is needed for nx affected to work when CI is running on a PR
        run: git branch --track main origin/main

      - run: npx nx format:check

      # requires kratos and keto to be running
      - run: npx nx affected -t lint,test,build --parallel=3
