name: CI
on:
  push:
    branches:
      - main
  pull_request:

env:
  CI: true

jobs:
  main:
    runs-on: ubuntu-latest

    services:
      kratos:
        image: ghcr.io/getlarge/nestjs-ory-integration/kratos:latest
        ports:
          - '44330:4433'
          - '44340:4434'

      keto:
        image: ghcr.io/getlarge/nestjs-ory-integration/keto:latest
        ports:
          - '44660:4466'
          - '44670:4467'

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Cache node_modules
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - run: npm ci

      - uses: nrwl/nx-set-shas@v4

      - uses: 8BitJonny/gh-get-current-pr@2.2.0
        id: current-pr

      - if: steps.current-pr.outputs.number != 'null'
        # This line is needed for nx affected to work when CI is running on a PR
        run: git branch --track main origin/main

      - run: npx nx format:check

      # requires kratos and keto to be running
      - run: npx nx affected -t lint,test,build --parallel=3
